import Sqids from 'sqids';
import { RedisService } from '../infrastructure/redis.service';
import { Injectable } from '@nestjs/common';

/**
 * Application service responsible for the core business logic of URL shortening.
 * Orchestrates the generation, caching, and resolution of short links.
 */
@Injectable()
export class ShortenerService {
  private readonly sqids: Sqids;

  constructor(private readonly redisService: RedisService) {
    this.sqids = new Sqids({ minLength: 6 });
  }

  /**
   * Shortens a given original URL.
   * Optimizes performance by returning the existing code if the URL was already shortened.
   * Generates a unique, collision-free short code using an atomic counter and Sqids.
   *
   * @param url The original, fully qualified URL to be shortened.
   * @returns A unique short code string (e.g., 'abc123').
   */
  async shorten(url: string): Promise<string> {
    const existingCode = await this.redisService.get(`original:${url}`);
    if (existingCode) return existingCode;

    const id = await this.redisService.getNextId();
    const code = this.sqids.encode([id]);

    await this.redisService.set(`link:${code}`, url);
    await this.redisService.set(`original:${url}`, code);

    return code;
  }

  /**
   * Resolves a short code back to its original target URL.
   *
   * @param code The unique short code generated by the system.
   * @returns The original URL string if found, or null if the code is invalid or does not exist.
   */
  async resolve(code: string): Promise<string | null> {
    return this.redisService.get(`link:${code}`);
  }
}
